### PR TITLE
Add support net7 and net8, update linux dependencies

### PR DESCRIPTION
**Pull request by DmitryShevchenko**
Support for Net7 and Net8 
Update linux dependencies
update yml files

### CODE REVIEW

**Comment by Andkago** [comment]
Is this tested and ok? 

I there anyone who can approve, and build new packages?

**Review by Andkago — APPROVED** [review]
This looks ok!

**Comment by flozano** [comment]
looking forward to have this available! I'm porting old .NET windows code to dotnet core 8.0, and my deployment target is RPM... it'd make it much easier!

**Comment by flozano** [comment]
in the meantime @DmitryShevchenko , is there any way to use the code from your fork? are you publishing the builds in any way?

**Comment by Andkago** [comment]
Tank you!

**Comment by flozano** [comment]
@qmfrederik thanks a lot for merging! I was looking at how to setup my own nuget repo which I don't have now 

do you plan to publish a release to public nuget which includes this?

**Comment by flozano** [comment]
I am looking at the azure pipeline definition and it seems it's supposed to publish to nuget on any commit to master? is that accurate?

**Comment by redflitzi** [comment]
Nuget gallery still says version is 0.1.220 as of 12/16/2021.

So no, it seems there is no automatic publishing to nuget.

**Comment by flozano** [comment]
yes, there are no published packages. there is an azure pipeline definition that seems to imply that the packages are published after building master: https://github.com/quamotion/dotnet-packaging/blob/master/.azure-pipelines.yml#L360

it'd be great to have them in nuget available

**Comment by redflitzi** [comment]
Thank you very much @qmfrederik !

**Pull request merged**
